# Sys.setenv("R_TESTS" = "")
# options(fftempdir = file.path(getwd(),'fftemp'))
library(testthat)
library(NSCLCCharacterization)
test_check("NSCLCCharacterization")
unlink("T:/Temp", recursive = T)
